name: Slash Command Listener

on:
  issue_comment:
    types:
      - created

jobs:
  process-command:
    runs-on: ubuntu-latest
    if: (github.event.comment.body == '/ok-to-test') || (github.event.comment.body == '/rerun')
    steps:
      - name: Check Slash Command and User Association
        id: check-condition
        run: |
          echo "slash_command=${{github.event.comment.body}}" >> $GITHUB_ENV
          if [[ "${{ github.event.comment.author_association }}" == "MEMBER" || "${{ github.event.comment.author_association }}" == "OWNER" ]]; then
            echo "condition_met=true" >> $GITHUB_ENV
          else
            echo "User does not have permission to trigger this command."
            echo "condition_met=false" >> $GITHUB_ENV
          fi

      # Comment if the condition is not met
      - name: Post Comment for Invalid Condition
        if: env.condition_met == 'false'
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: 🚫 This command cannot be processed. Only organization members or owners can use the commands.

      # Approve Run if the condition is met
      - name: Approve Run
        id: approve
        if: env.condition_met == 'true' && (github.event.comment.body == '/ok-to-test')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the PR head SHA
          pr_sha=${{ github.event.issue.pull_request.head.sha }}
          
          # Get the run_id of the current workflow run
          runs=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?head_sha=$pr_sha" | \
            jq -r '.workflow_runs[] | select(.conclusion == "action_required") | .id')

          # Approve the workflow run
          if [[ -z "$runs" ]]; then
            msg="No workflow runs requiring approval detected for this Pull Request."
            echo "output_msg=${msg}" >> $GITHUB_ENV
          else
            echo "Found workflow runs requiring approval: $runs"
            # Approve each workflow run
            for run_id in $runs; do
              curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/approve"
              msg="Approved workflow run: $run_id" 
              echo "output_msg=${msg}" >> $GITHUB_ENV
            done
          fi

      - name: Post Comment for Invalid Condition
        if: (steps.approve.outcome == 'success') && env.output_msg
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: ${{ env.output_msg }}

      - name: Re-Run
        id: rerun
        if: env.condition_met == 'true' && (github.event.comment.body == '/rerun')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo rerun