name: Slash Command Listener

on:
  issue_comment:
    types:
      - created

jobs:
  process-command:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.event.comment.body, '/ok-to-test') && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')
    steps:
      - name: Dispatch Workflow
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: ok-to-test
          args: ${{ github.event.issue.number }}
